-- LegalMind Yemen — Supabase Schema Entry Point
-- For a fresh Supabase project, run the complete schema:
--   supabase/complete_schema.sql
--
-- For incremental updates, use migrations in order:
--   supabase/migrations/001_production_schema.sql
--   supabase/migrations/002_multi_tenant_offices.sql
--   supabase/migrations/003_offline_sync.sql
--   supabase/migrations/004_auth_redesign_offices_profiles.sql
--   supabase/migrations/005_complete_invitation_system.sql
--   supabase/migrations/006_backend_stability_helpers.sql
--   supabase/migrations/007_firm_codes.sql
